version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-app
    restart: unless-stopped  
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy  
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: unless-stopped  
    ports:
      - "8080:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registro_ponto
      MYSQL_USER: app_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      timeout: 5s

  n8n:
    image: n8nio/n8n
    container_name: n8n-automation
    restart: unless-stopped  
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      mysql:
        condition: service_healthy 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  n8n_data:
